Fix query aphp
medInria/qtdcm pull request #4
Opened 2021-01-15 16:22 UTC by juliencastelneau

Some debug:
- C-Find
- C-Move (Patient/Study/Series Query Level)
- Debug Filters in UI

Specifics devs for medInria in APHP context.

2021-01-22 09:14 UTC, Florent2305 requested changes
Ok but check date behavior.

2021-01-22 09:14 UTC, Florent2305 commented on src/QtDcmManager.cpp
> +    finder->findStudiesScu ( patientId, patientName, d->studyDescription, d->startDate.toString( "yyyyMMdd" ), d->endDate.toString( "yyyyMMdd" ));
Attention certaines anonymizations enlèvent totalement les dates.
Pour pouvoir récupérer des datasets sans dates, il faut soit '*' soit vide.

Est-ce que ce point a bien été testé ?
J'ai peur qu'avec  `toString( "yyyyMMdd" )`  '*' ou empty ne passe pas ou mal.

2021-01-25 13:22 UTC, juliencastelneau commented on src/QtDcmManager.cpp
> +    finder->findStudiesScu ( patientId, patientName, d->studyDescription, d->startDate.toString( "yyyyMMdd" ), d->endDate.toString( "yyyyMMdd" ));
Ok. I push a fix

2021-01-25 13:52 UTC, juliencastelneau commented
Follow rules for Study Date  from 
- http://dicom.nema.org/medical/Dicom/2017c/output/chtml/part04/sect_C.2.2.2.5.html

2021-01-25 15:44 UTC, Florent2305 approved these changes
ok

2021-01-25 15:45 UTC, merged